/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for DOUBLE_QUOTE Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.python.ast;

import org.parsers.python.*;
import static org.parsers.python.Token.TokenType.*;


public class DOUBLE_QUOTE extends Token {

    public DOUBLE_QUOTE(TokenType type, PythonLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


