/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for FSTRING_DOUBLE_QUOTE_START Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.python.ast;

import org.parsers.python.*;
import static org.parsers.python.Token.TokenType.*;


public class FSTRING_DOUBLE_QUOTE_START extends Token {

    public FSTRING_DOUBLE_QUOTE_START(TokenType type, PythonLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


