/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Name Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.python.ast;

import org.parsers.python.*;
import static org.parsers.python.Token.TokenType.*;


public class Name extends Token {

    public Name(TokenType type, PythonLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


