/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for ReturnStatement AST Node type
* by the ASTNode.java.ftl template
*/
package org.parsers.python.ast;

import org.parsers.python.*;
import java.util.*;
import static org.parsers.python.Token.TokenType.*;


public class ReturnStatement extends BaseNode {
}


